### ISSUE TITLE
Usage of import java.util.Date in Java && java-Simple is deprecated

### ISSUE THREAD

**Issue by Fabinout** [martinsson/Refactoring-Kata-Lift-Pass-Pricing#26]
I don't know if it's "by-design" to have deprecated code in a refactoring kata, but if you want, I can fix it.

**Comment by codecop** [comment]
Thank you, refactoring katas often contain older versions of language or libraries - because that is how it is in real life too. While it is not in the nature of this exercise, I would leave it alone to stay similar to other languages.

**Comment by codecop** [comment]
@martinsson vote to close
